name: orientation_listener
description: >-
  A lightweight Flutter package for listening to device orientation changes
  (portrait/landscape) without needing a BuildContext.
version: 0.1.0
homepage: https://github.com/Elshan2022/orientation_listener
repository: https://github.com/Elshan2022/orientation_listener
issue_tracker: https://github.com/Elshan2022/orientation_listener/issues

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

topics:
  - orientation
  - sensors
  - device
  - listener
  - utility
